### PR TITLE
A simpler and functionl version for Problem 14

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by lilyball** [comment]
This is a collection of personal solutions to Project Euler problems from 11 years ago. While you're more than welcome to peruse through them, it's not meant to be a repository of ideal solutions or anything like that. I'm just going to go ahead and turn off pull requests entirely.

**Comment by lilyball** [comment]
Apparently I can't turn off pull requests. Oh well. Still, the point remains.

**Comment by ghost** [comment]
You should archive it, maybe?

**Comment by lilyball** [comment]
Good idea. I didn't realize that was an option.

**Pull request closed without merging**
